include ~/.cache/ignis/material/dark_colors-kitty.conf

# -------- GENERAL ------------

# FONT
font_family JetBrainsMono Nerd Font Mono
font_size 12

# STYLE
background_opacity 1
window_padding_width 15
tab_bar_edge top
tab_bar_style powerline

# BEHAVIOUR
remember_window_size no
shell_integration no-rc
enabled_layouts splits 

# --------- KEYMAPS -------------

map --new-mode mt ctrl+space
map --mode mt esc pop_keyboard_mode

# TABS
map --mode mt p previous_tab
map --mode mt n next_tab
map --mode mt q close_tab
map --mode mt t new_tab

map --mode mt 1 goto_tab 1
map --mode mt 2 goto_tab 2
map --mode mt 3 goto_tab 3
map --mode mt 4 goto_tab 4
map --mode mt 5 goto_tab 5

map --mode mt , set_tab_title

# SPLITS
map --mode mt v launch --location=vsplit
map --mode mt s launch --location=hsplit

map --mode mt h neighboring_window left
map --mode mt j neighboring_window down
map --mode mt k neighboring_window up
map --mode mt l neighboring_window right

map --mode mt x close_window

map --mode mt shift+h resize_window narrower
map --mode mt shift+j resize_window shorter
map --mode mt shift+k resize_window taller
map --mode mt shift+l resize_window wider

# MISC
map --mode mt [ show_scrollback
