include ~/.cache/ignis/material/dark_colors-kitty.conf

# -------- GENERAL ------------

# FONT
font_family JetBrainsMono Nerd Font Mono
font_size 12

# STYLE
background_opacity 1
window_padding_width 15
tab_bar_edge top
tab_bar_style powerline

# BEHAVIOUR
remember_window_size no
shell_integration no-rc
enabled_layouts splits 

# --------- KEYMAPS -------------


# TABS
map ctrl+space>h previous_tab
map ctrl+space>l next_tab
map ctrl+space>q close_tab
map ctrl+space>t new_tab

map ctrl+space>1 goto_tab 1
map ctrl+space>2 goto_tab 2
map ctrl+space>3 goto_tab 3
map ctrl+space>4 goto_tab 4
map ctrl+space>5 goto_tab 5

map ctrl+space>, set_tab_title

# SPLITS
map ctrl+space>v launch --location=vsplit
map ctrl+space>s launch --location=hsplit

map ctrl+space>n neighboring_window left
map ctrl+space>j neighboring_window down
map ctrl+space>k neighboring_window up
map ctrl+space>p neighboring_window right

map ctrl+space>x close_window

map ctrl+space>shift+h resize_window narrower
map ctrl+space>shift+j resize_window shorter
map ctrl+space>shift+k resize_window taller
map ctrl+space>shift+l resize_window wider

# MISC
map ctrl+space>[ show_scrollback
